name: Deploy to NetSuite

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install SuiteCloud CLI
        run: npm install -g @oracle/suitecloud-cli --acceptsuitecloudsdklicense

      - name: Authenticate using Token Auth
        run: |
          suitecloud account:setup:tokenauth \
            --account ${{ secrets.NETSUITE_ACCOUNT }} \
            --consumerkey ${{ secrets.NETSUITE_CONSUMER_KEY }} \
            --consumersecret ${{ secrets.NETSUITE_CONSUMER_SECRET }} \
            --tokenid ${{ secrets.NETSUITE_TOKEN_ID }} \
            --tokensecret ${{ secrets.NETSUITE_TOKEN_SECRET }}

          suitecloud account:saveasauthid --authid github-deploy-auth

      - name: Deploy project
        run: suitecloud project:deploy --authid github-deploy-auth
