name: Deploy to NetSuite with JWT

on:
  push:
    branches: [main]
    paths:
      - '**.js'  # Only trigger on JavaScript file changes
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Deploy to NetSuite
        run: node multiplier_netsuite_deployment.js
        env:
          ACCOUNT_ID: ${{ secrets.NETSUITE_ACCOUNT_ID }}
          BASE_URL: ${{ secrets.NETSUITE_BASE_URL }}
          CONSUMER_KEY: ${{ secrets.NETSUITE_CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.NETSUITE_CONSUMER_SECRET }}
          TOKEN_ID: ${{ secrets.NETSUITE_TOKEN_ID }}
          TOKEN_SECRET: ${{ secrets.NETSUITE_TOKEN_SECRET }}
          JWT_PRIVATE_KEY: ${{ secrets.NETSUITE_JWT_PRIVATE_KEY }}
          JWT_KEY_ID: ${{ secrets.NETSUITE_JWT_KEY_ID }}
