name: NetSuite Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_mode:
        description: 'Deployment mode'
        required: true
        default: 'validate_and_deploy'
        type: choice
        options:
          - validate_only
          - deploy_only
          - validate_and_deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Netsuite Sandbox

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install global dependencies
        run: |
          npm install -g @oracle/suitecloud-cli
          npm install -g typescript

      - name: Install project dependencies
        run: |
          if [ -f "package.json" ]; then
            npm ci
          else
            echo "No package.json found, skipping npm ci"
          fi

      - name: Make deployment script executable
        run: chmod +x ./multiplier_github_netsuite_deployment.sh

      - name: List directory contents
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          
      - name: Deploy to Sandbox
        env:
          NS_ACCOUNT: ${{ secrets.SANDBOX_ACCOUNT }}
          NS_CONSUMER_KEY: ${{ secrets.SANDBOX_CONSUMER_KEY }}
          NS_CERTIFICATE_ID: ${{ secrets.NS_CERTIFICATE_ID }}
          NS_PRIVATE_KEY: ${{ secrets.NS_PRIVATE_KEY }}
        run: |
          echo "Running deployment script with environment: sandbox"
          echo "Project directory structure:"
          ls -la
          ./multiplier_github_netsuite_deployment.sh \
            --environment sandbox \
            --mode ${{ github.event.inputs.deploy_mode || 'validate_and_deploy' }} \
            --directory multiplier-netsuite-integration

      - name: Notify deployment status
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: netsuite-deployments
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: NetSuite Deployment Status
          SLACK_MESSAGE: "Deployment to sandbox ${{ job.status }}"
